#!/usr/bin/env python3
"""
gen-mechanic-db.py — emits src/data/MechanicDb.gen.{h,cpp} from
docs/data/dungeon-mechanic-db.csv.

Phase 2 codegen for the cata-altbot encounter pipeline. The generated table
is a sorted-by-spell_id constexpr array consumed by `EncounterMechanics::Lookup`.

Filters used by the avoidable rows (the only rows Phase 2 ships):
  - mechanic_class == "avoidable"
  - status in {"verified", "unbound"}   (DBC-name-match required;
    "unbound" rows pass because many TC bosses are empty stubs and the
    spell ID can still be authoritative per DBC.)

Re-run by hand whenever the CSV changes; the generated files are checked in.
"""
import csv
import os
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_PATH  = REPO_ROOT / "docs" / "data" / "dungeon-mechanic-db.csv"
OUT_DIR   = REPO_ROOT / "src" / "data"
OUT_H     = OUT_DIR / "MechanicDb.gen.h"
OUT_CPP   = OUT_DIR / "MechanicDb.gen.cpp"

DEFAULT_AVOID_RADIUS_Y = 6.0   # plain ground-patch fallback; per-row override wins
ACCEPTED_STATUSES      = {"verified", "unbound"}

# Map dispel_type strings from the YAML / DBC into a stable enum value.
DISPEL_ENUM = {
    "":               "None",
    "none":           "None",
    "magic":          "Magic",
    "curse":          "Curse",
    "poison":         "Poison",
    "disease":        "Disease",
    "enrage_purge":   "EnragePurge",
    "magic_offensive":"MagicOffensive",   # purge / spellsteal
}

PRIORITY_ENUM = {
    "":                          "Default",
    "MUST_INTERRUPT":            "MustInterrupt",
    "SHOULD_INTERRUPT":          "ShouldInterrupt",
    "HIGH_DISPEL":               "HighDispel",
    "SHOULD_DISPEL":             "ShouldDispel",
    "HIGHEST_DISPEL_OFFENSIVE":  "HighestDispelOffensive",
    "TANK_KITE_TRIGGER":         "Default",
    "TANK_BURST_DEFENSIVE":      "Default",
    "MELEE_POSITIONING_RULE":    "Default",
    "SELF_MANAGED_POSITIONING":  "Default",
    "KILL_ON_SIGHT":             "Default",
    "CRITICAL_DPS_SWITCH":       "Default",
    "CRITICAL":                  "Default",
}

def parse_float(val, default):
    try:
        return float(val)
    except (TypeError, ValueError):
        return default

def main():
    if not CSV_PATH.exists():
        raise SystemExit(f"input CSV missing: {CSV_PATH}")

    with open(CSV_PATH, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    # Avoidable rows for Phase 2.
    avoidable = []
    for r in rows:
        if r["mechanic_class"] != "avoidable":
            continue
        if r["status"] not in ACCEPTED_STATUSES:
            continue
        sid = r["spell_id"]
        if not sid or not sid.isdigit():
            continue
        avoidable.append(r)

    # Deduplicate by spell_id — same ID across dungeons is allowed but we only
    # emit one row per ID (the first encountered after sort).
    seen = set()
    deduped = []
    for r in sorted(avoidable, key=lambda r: int(r["spell_id"])):
        sid = int(r["spell_id"])
        if sid in seen:
            continue
        seen.add(sid)
        deduped.append(r)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Generate header.
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write(_HEADER_PROLOGUE)
        f.write(f"\nstatic constexpr std::size_t kMechanicDbSize = {len(deduped)};\n")
        f.write(_HEADER_EPILOGUE)

    # Generate cpp.
    with open(OUT_CPP, "w", encoding="utf-8") as f:
        f.write(_CPP_PROLOGUE)
        for r in deduped:
            sid = int(r["spell_id"])
            name = r["spell_name_dbc"].replace('"', '\\"') or r["spell_name_doc"].replace('"', '\\"')
            radius = parse_float(r["avoid_radius_y"], DEFAULT_AVOID_RADIUS_Y)
            slug = r["dungeon_slug"] or "?"
            mob = (r["boss_or_mob"] or "?").replace('"', '\\"')
            f.write(f'    {{ {sid:>7}, {radius:>5.1f}f, MechanicClass::Avoidable, '
                    f'DispelType::None, InterruptPriority::Default, '
                    f'"{slug}", "{mob}", "{name}" }},  // {r["status"]}\n')
        f.write(_CPP_EPILOGUE)

    print(f"  emitted {OUT_H} ({len(deduped)} rows)")
    print(f"  emitted {OUT_CPP}")

_HEADER_PROLOGUE = '''// AUTO-GENERATED by tools/gen-mechanic-db.py — DO NOT EDIT BY HAND.
// Source of truth: docs/data/dungeon-mechanic-db.csv.
//
// Re-run with:
//     python3 tools/gen-mechanic-db.py
//
// Sorted-by-spell_id constexpr table consumed via lower_bound by
// `EncounterMechanics::Lookup`. The runtime API lives in EncounterMechanics.h;
// nothing else should include this header.
#pragma once
#include <cstddef>
#include <cstdint>

namespace AltbotMechanicDb
{
    enum class MechanicClass : uint8_t
    {
        Avoidable = 1,
        Interrupt = 2,
        Dispel    = 3,
        Phase     = 4,
    };

    enum class DispelType : uint8_t
    {
        None             = 0,
        Magic            = 1,
        Curse            = 2,
        Poison           = 3,
        Disease          = 4,
        EnragePurge      = 5,
        MagicOffensive   = 6,
    };

    enum class InterruptPriority : uint8_t
    {
        Default                = 0,
        ShouldInterrupt        = 1,
        MustInterrupt          = 2,
        ShouldDispel           = 3,
        HighDispel             = 4,
        HighestDispelOffensive = 5,
    };

    struct MechanicEntry
    {
        uint32             spellId;
        float              avoidRadiusY;
        MechanicClass      mclass;
        DispelType         dispel;
        InterruptPriority  priority;
        char const*        dungeonSlug;
        char const*        bossOrMob;
        char const*        spellName;
    };
'''

_HEADER_EPILOGUE = '''
    // Defined in MechanicDb.gen.cpp.
    extern MechanicEntry const kMechanicDb[];
}
'''

_CPP_PROLOGUE = '''// AUTO-GENERATED by tools/gen-mechanic-db.py — DO NOT EDIT BY HAND.
#include "MechanicDb.gen.h"

namespace AltbotMechanicDb
{
    MechanicEntry const kMechanicDb[] = {
'''

_CPP_EPILOGUE = '''    };
}
'''

if __name__ == "__main__":
    main()
