#!/usr/bin/env python3
"""
scaffold-strategy.py — emit boilerplate src/strategies/{Spec}Strategy.{h,cpp}.

Phase 5 onboarding tool. Copies the structural skeleton (class declaration,
ResolveSpellCache, TryCast / IsOnCooldown, DoMaintenance / DoDefensives,
Update() with cast-in-progress + GCD guards) used by the 4 existing
strategies, with TODO markers where the per-spec rotation tier methods go.

Inputs (CLI flags, all required):
  --class      class slug (e.g. WARLOCK, MAGE, PALADIN)
  --tree       TalentTab.dbc ID for this spec (verify via WDBXEditor)
  --slug       file slug (e.g. demonology-warlock, holy-paladin)
  --role       healer | ranged-dps | melee-dps | tank
  --filler     primary GCD-bucket spell name for the filler/probe (e.g. "Shadow Bolt")

Outputs:
  src/strategies/{ClassName}Strategy.{h,cpp}
  diff snippet for AltbotStrategyFactory.cpp printed to stdout
  checklist of follow-up steps printed to stdout

Re-run is safe — files are overwritten only after a confirmation prompt.
"""
import argparse
import os
import re
import string
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STRAT_DIR = REPO_ROOT / "src" / "strategies"

CLASSNAME_FROM_SLUG = lambda slug: "".join(p.capitalize() for p in re.split(r"[-_]+", slug)) + "Strategy"
SPEC_LABEL_FROM_SLUG = lambda slug: "".join(p.capitalize() for p in re.split(r"[-_]+", slug))

# ---- header template ----
H_TEMPLATE = string.Template(r"""#pragma once
#include "AltbotStrategy.h"
#include <array>
#include <cstdint>

class Player;
class Unit;

// $classname — TODO(rotation): autogenerated scaffold by tools/scaffold-strategy.py.
//
// Replace the Spell enum and tier methods with the spec rotation per
// docs/specs/$slug.md. See FrostMageStrategy / MmHunterStrategy / etc. for
// reference patterns. The cast pipeline gotchas in CLAUDE.md (passive talent
// name collisions, cast-in-progress + GCD guards, every cast through
// CastWithLog) all apply here.
class $classname : public AltbotStrategy
{
public:
    $classname() = default;

    void         Update(Player* bot, Player* master, AltbotTickContext const& ctx) override;
    char const*  GetName() const override { return "$slug"; }

    void InvalidateCache() { _cacheResolved = false; _cache.fill(0); }

private:
    enum class Spell : uint8_t
    {
        // TODO(rotation): list every spell the rotation references.
        // The Filler entry is required — the ctor uses its cooldown info
        // for the post-cast GCD probe in Update().
        Filler = 0,
        Count
    };

    std::array<uint32, size_t(Spell::Count)> _cache{};
    bool _cacheResolved = false;

    uint32 GetSpell(Spell s) const { return _cache[size_t(s)]; }
    void   ResolveSpellCache(Player* bot);

    bool TryCast(Player* bot, Unit* target, Spell s) const;
    bool IsOnCooldown(Player* bot, uint32 spellId) const;

    void DoMaintenance(Player* bot);
    bool DoDefensives(Player* bot);

    // TODO(rotation): one Tier_X per priority slot.
};
""")

# ---- cpp template ----
CPP_TEMPLATE = string.Template(r"""#include "$classname.h"
#include "AltbotCombatLog.h"
#include "AltbotPosition.h"
#include "AltbotPositionManager.h"
#include "AltbotTickContext.h"
#include "Log.h"
#include "Player.h"
#include "SpellHistory.h"
#include "SpellInfo.h"
#include "SpellMgr.h"
#include "Unit.h"
#include "strategies/StrategyUtil.h"

namespace
{
    constexpr char const* SPEC_LABEL = "$spec_label";

    // TODO(rotation): per-spec constants here (HP gates, range cutoffs, etc.).
    constexpr float DESIRED_RANGE_Y = 25.0f;
    constexpr uint32 ROTATION_THREAT_WINDOW_MS = 2000;
}

void $classname::Update(Player* bot, Player* master, AltbotTickContext const& ctx)
{
    if (!bot || !master || !bot->IsAlive())
        return;

    Unit* target = master->GetSelectedUnit();
    if (!target || !target->IsAlive())
        return;

    if (!_cacheResolved)
    {
        ResolveSpellCache(bot);
        _cacheResolved = true;
    }

    DoMaintenance(bot);

    if (DoDefensives(bot))
        return;

    // Cast pipeline gotcha 3: skip the rotation while a cast is in progress
    // (channels covered by IsNonMeleeSpellCast(false), regular casts by
    // UNIT_STATE_CASTING). Without this every long cast gets re-issued each
    // tick and fails with SPELL_FAILED_SPELL_IN_PROGRESS.
    if (bot->HasUnitState(UNIT_STATE_CASTING) || bot->IsNonMeleeSpellCast(false))
        return;

    // Cast pipeline gotcha 4: skip the rotation while the GCD is active.
    // GCD is invisible to IsCasting; HasGlobalCooldown is keyed by
    // StartRecoveryCategory so any standard-bucket spell works as the probe.
    if (uint32 fillerId = GetSpell(Spell::Filler))
    {
        SpellInfo const* fillerInfo = sSpellMgr->GetSpellInfo(fillerId);
        if (fillerInfo && bot->GetSpellHistory()->HasGlobalCooldown(fillerInfo))
            return;
    }

    // Threat-window gate: $role-aware DPS waits 2s for the tank to settle
    // threat before opening the rotation. Healers / pet-tanks override.
    if (ctx.combatElapsedMs < ROTATION_THREAT_WINDOW_MS && ctx.InInstance())
        return;

    // Maintain caster range when applicable. Healers should *not* call this —
    // they stay near master / party for AoE-heal radius. Melee specs delete.
    if (ctx.positionManager)
        ctx.positionManager->SetIntent(
            AltbotPositionManager::MakeRangedDpsIntent(target, master));

    // TODO(rotation): tier dispatch. Set tier metadata before each Tier_X
    // check so the AltbotCombatLog telemetry can attribute the cast:
    //
    //   AltbotCombatLog::SetCurrentTier(0, "TierName");
    //   if (Tier_Foo(bot, target)) return;
    //
    AltbotCombatLog::OnNoTierFired(bot, SPEC_LABEL);
}

void $classname::ResolveSpellCache(Player* bot)
{
    _cache.fill(0);
    auto find = [bot](char const* name) {
        return StrategyUtil::FindSpellByFamilyName(bot, /*TODO: SPELLFAMILY_X*/ 0, name);
    };
    // TODO(rotation): _cache[size_t(Spell::Filler)] = find("$filler");
    (void)find;
    TC_LOG_INFO("altbot", "%s[%s] cache resolved", SPEC_LABEL, bot->GetName().c_str());
}

bool $classname::TryCast(Player* bot, Unit* target, Spell s) const
{
    uint32 id = GetSpell(s);
    if (!id || !target)
        return false;
    SpellInfo const* info = sSpellMgr->GetSpellInfo(id);
    if (!info || bot->GetSpellHistory()->HasCooldown(info))
        return false;
    return StrategyUtil::CastWithLog(bot, target, id, SPEC_LABEL) == SPELL_CAST_OK;
}

bool $classname::IsOnCooldown(Player* bot, uint32 spellId) const
{
    if (!spellId) return true;
    SpellInfo const* info = sSpellMgr->GetSpellInfo(spellId);
    if (!info) return true;
    return bot->GetSpellHistory()->HasCooldown(info);
}

void $classname::DoMaintenance(Player* /*bot*/)
{
    // TODO(rotation): armor / weapon imbue / aspect / aura maintenance.
}

bool $classname::DoDefensives(Player* /*bot*/)
{
    // TODO(rotation): emergency self-defenses (Ice Block, Soulburn, Deterrence,
    // displacement *only* when meleeNear>=2 && hp<60% — see CLAUDE.md gotcha #6).
    return false;
}
""")

FACTORY_DIFF_TEMPLATE = string.Template(r"""// --- snippet for src/AltbotStrategyFactory.cpp -----------------------------
//
// 1. Add #include line at the top:
//        #include "strategies/$classname.h"
//
// 2. Add the talent tree constant alongside the others:
//        static constexpr uint32 ${class_const}_TREE_${tree_const} = $tree_id;
//
// 3. In SlugFromBot, in the appropriate `else if (cls == CLASS_$class_upper)`
//    block, add:
//        if (tree == ${class_const}_TREE_${tree_const}) return "$slug";
//
// 4. In Create(), add:
//        if (slug == "$slug")
//            return std::make_unique<$classname>();
//
// ---------------------------------------------------------------------------
""")

CHECKLIST_TEMPLATE = string.Template(r"""
$classname scaffold complete. Follow-up checklist:

  [ ] Verify TalentTab.dbc id $tree_id for $slug via WDBXEditor (the original
      Cata launch IDs in older guides are usually wrong — see
      docs/research/dbc-verification-checklist.md).

  [ ] Replace the `Spell` enum with the spell list from docs/specs/$slug.md.

  [ ] In ResolveSpellCache, pick a `find()` strategy:
      - effect-introspection (pattern: RestoShamanStrategy) when each spell
        has a unique effect signature.
      - StrategyUtil::FindSpellByFamilyName(bot, SPELLFAMILY_X, "Spell Name")
        otherwise (warlock DoTs, mage school overlap, hunter focus
        rotation). Verify SPELLFAMILY_X for the class.

  [ ] Populate Tier_X methods per the rotation in docs/specs/$slug.md.
      Use SetCurrentTier(idx, name) at the dispatch site so the cast lands
      in telemetry with a stable tier label.

  [ ] Apply CLAUDE.md cast pipeline gotchas:
        1. Filter passive talents in name-walk helpers (info->IsPassive()).
        2. Every cast through StrategyUtil::CastWithLog.
        3. Cast-in-progress guard (already in scaffold).
        4. GCD probe (already in scaffold).
        5. MaintainRange only for ranged casters; preserve the idempotency
           guard in AltbotPosition::MaintainRange.

  [ ] Wire into the factory using the snippet printed above.

  [ ] Add a Phase-1 telemetry smoke test:
      casts/min target met, GCD utilization >= 85%, no_tier_ticks == 0
      after combat enters.
""")

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--class",       required=True, dest="cls",
                   help="Class name slug (e.g. WARLOCK, MAGE, PRIEST)")
    p.add_argument("--tree",        required=True, type=int,
                   help="TalentTab.dbc ID for this spec")
    p.add_argument("--slug",        required=True,
                   help="File slug (e.g. demonology-warlock, holy-paladin)")
    p.add_argument("--role",        required=True,
                   choices=["healer", "ranged-dps", "melee-dps", "tank"])
    p.add_argument("--filler",      required=True,
                   help="Primary filler/probe spell name (used by GCD probe)")
    p.add_argument("--force",       action="store_true",
                   help="Overwrite existing files without prompting")
    args = p.parse_args()

    classname  = CLASSNAME_FROM_SLUG(args.slug)
    spec_label = SPEC_LABEL_FROM_SLUG(args.slug)
    tree_const = args.slug.split("-")[0].upper()    # affliction-warlock -> AFFLICTION

    h_path   = STRAT_DIR / f"{classname}.h"
    cpp_path = STRAT_DIR / f"{classname}.cpp"

    for path in (h_path, cpp_path):
        if path.exists() and not args.force:
            raise SystemExit(f"refusing to overwrite existing {path} (pass --force)")

    STRAT_DIR.mkdir(parents=True, exist_ok=True)

    h_path.write_text(H_TEMPLATE.substitute(
        classname=classname, slug=args.slug))
    cpp_path.write_text(CPP_TEMPLATE.substitute(
        classname=classname, slug=args.slug, role=args.role,
        spec_label=spec_label, filler=args.filler))

    print(f"  wrote {h_path}")
    print(f"  wrote {cpp_path}")
    print()
    print(FACTORY_DIFF_TEMPLATE.substitute(
        classname=classname, slug=args.slug,
        class_const=tree_const, class_upper=args.cls.upper(),
        tree_const="TREE", tree_id=args.tree))
    print(CHECKLIST_TEMPLATE.substitute(
        classname=classname, slug=args.slug, tree_id=args.tree))

if __name__ == "__main__":
    main()
