// AUTO-GENERATED by tools/gen-mechanic-db.py — DO NOT EDIT BY HAND.
// Source of truth: docs/data/dungeon-mechanic-db.csv.
//
// Re-run with:
//     python3 tools/gen-mechanic-db.py
//
// Sorted-by-spell_id constexpr table consumed via lower_bound by
// `EncounterMechanics::Lookup`. The runtime API lives in EncounterMechanics.h;
// nothing else should include this header.
#pragma once
#include <cstddef>
#include <cstdint>

namespace AltbotMechanicDb
{
    enum class MechanicClass : uint8_t
    {
        Avoidable = 1,
        Interrupt = 2,
        Dispel    = 3,
        Phase     = 4,
    };

    enum class DispelType : uint8_t
    {
        None             = 0,
        Magic            = 1,
        Curse            = 2,
        Poison           = 3,
        Disease          = 4,
        EnragePurge      = 5,
        MagicOffensive   = 6,
    };

    enum class InterruptPriority : uint8_t
    {
        Default                = 0,
        ShouldInterrupt        = 1,
        MustInterrupt          = 2,
        ShouldDispel           = 3,
        HighDispel             = 4,
        HighestDispelOffensive = 5,
    };

    struct MechanicEntry
    {
        uint32             spellId;
        float              avoidRadiusY;
        MechanicClass      mclass;
        DispelType         dispel;
        InterruptPriority  priority;
        char const*        dungeonSlug;
        char const*        bossOrMob;
        char const*        spellName;
    };

static constexpr std::size_t kMechanicDbSize = 149;

    // Defined in MechanicDb.gen.cpp.
    extern MechanicEntry const kMechanicDb[];
}
