// AUTO-GENERATED by tools/gen-mechanic-db.py — DO NOT EDIT BY HAND.
#include "MechanicDb.gen.h"

namespace AltbotMechanicDb
{
    MechanicEntry const kMechanicDb[] = {
    {    1680,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "lockmaw", "Whirlwind" },  // unbound
    {    1943,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "ozruk", "Rupture" },  // unbound
    {    7964,   5.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "lockmaw", "Smoke Bomb" },  // unbound
    {   24236,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-aman", "daakara", "Whirlwind" },  // unbound
    {   42621,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-aman", "jan_alai", "Fire Bomb" },  // verified
    {   43140,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-aman", "jan_alai", "Flame Breath" },  // verified
    {   43267,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-aman", "halazzi", "Saber Lash" },  // unbound
    {   43622,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-aman", "akil_zon", "Static Disruption" },  // verified
    {   45101,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "forgemaster_throngus", "Flaming Arrow" },  // unbound
    {   65279,  10.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Lightning Nova" },  // unbound
    {   74108,   4.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "rajh", "Solar Winds" },  // unbound
    {   74136,  50.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "isiset", "Supernova" },  // verified
    {   74634,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "general_umbriss", "Ground Siege" },  // verified
    {   74670,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "general_umbriss", "Blitz" },  // verified
    {   74987,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "forgemaster_throngus", "Cave In" },  // verified
    {   75117,   4.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "temple_guardian_anhuur", "Burning Light" },  // unbound
    {   75238,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "drahga_shadowburner", "Supernova" },  // unbound
    {   75271,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "drahga_shadowburner", "Shredding Swipe" },  // verified
    {   75317,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "drahga_shadowburner", "Seeping Twilight" },  // unbound
    {   75339,   4.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "earthrager_ptah", "Earth Spike" },  // unbound
    {   75543,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "blackrock-caverns", "rom_ogg_bonecrusher", "The Skullcracker" },  // verified
    {   75547,   7.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "earthrager_ptah", "Quicksand" },  // unbound
    {   75592,   7.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "temple_guardian_anhuur", "Divine Reckoning" },  // verified
    {   75694,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "erudax_duke_of_below", "Shadow Gale" },  // unbound
    {   75702,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "ammunae", "Noxious Spores" },  // unbound
    {   75722,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "lady_nazjar", "Summon Geyser" },  // verified
    {   75732,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "blackrock-caverns", "corla_herald_of_twilight", "Twilight Evolution" },  // verified
    {   75907,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "Tainted Sentry", "Arc Slash" },  // verified
    {   76001,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "lady_nazjar", "Fungal Spores" },  // verified
    {   76030,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "blackrock-caverns", "beauty", "Berserker Charge" },  // verified
    {   76032,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "blackrock-caverns", "beauty", "Flamebreak" },  // verified
    {   76047,   7.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "commander_ulthok", "Dark Fissure" },  // verified
    {   76170,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "mindbender_ghursha", "Magma Splash" },  // unbound
    {   76184,   5.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "anraphet", "Alpha Beams" },  // verified
    {   76230,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "mindbender_ghursha", "Mind Fog" },  // unbound
    {   76681,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "setesh", "Chaos Blast" },  // verified
    {   77030,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "setesh", "Reign of Chaos" },  // unbound
    {   77715,   5.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "ozruk", "Shatter" },  // unbound
    {   78903,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "ozruk", "Ground Slam" },  // verified
    {   79002,   3.5f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "high_priestess_azil", "Seismic Shard" },  // verified
    {   79249,  10.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "high_priestess_azil", "Gravity Well" },  // verified
    {   79466,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "grim-batol", "erudax_duke_of_below", "Binding Shadows" },  // verified
    {   80643,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "slabhide", "Stalactite" },  // verified
    {   80803,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "slabhide", "Lava Fissure" },  // verified
    {   80807,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "slabhide", "Sand Blast" },  // verified
    {   81630,   5.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "lockmaw", "Viscous Poison" },  // verified
    {   81644,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "lockmaw", "Dust Flail" },  // unbound
    {   81828,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "corborus", "Thrashing Charge" },  // verified
    {   81942,  12.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "high_prophet_barim", "Heaven's Fury" },  // unbound
    {   82263,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "high_prophet_barim", "Merged Souls" },  // verified
    {   83051,   5.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Cloud Burst" },  // unbound
    {   83066,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Wailing Winds" },  // verified
    {   83171,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "general_husam", "Mystic Trap" },  // verified
    {   83445,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "general_husam", "Shockwave" },  // verified
    {   83446,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Tempest Storm" },  // unbound
    {   83561,  10.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "ozumat", "Blight of Ozumat" },  // unbound
    {   83650,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "earthrager_ptah", "Raging Smash" },  // verified
    {   84522,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Thunder Crash" },  // unbound
    {   84931,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "throne-of-the-tides", "mindbender_ghursha", "Earth Shards" },  // unbound
    {   84987,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Gathered Storms" },  // unbound
    {   86292,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-vortex-pinnacle", "grand_vizier_ertan", "Cyclone Shield" },  // unbound
    {   86309,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-vortex-pinnacle", "grand_vizier_ertan", "Storm's Edge" },  // unbound
    {   86881,   5.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "corborus", "Crystal Barrage" },  // verified
    {   86930,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-vortex-pinnacle", "asaad_caliph_of_zephyrs", "Supremacy of the Storm" },  // verified
    {   87622,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-vortex-pinnacle", "asaad_caliph_of_zephyrs", "Chain Lightning" },  // verified
    {   88308,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-vortex-pinnacle", "altairus", "Chilling Breath" },  // unbound
    {   88314,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-vortex-pinnacle", "altairus", "Twisting Winds" },  // unbound
    {   89131,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "halls-of-origination", "rajh", "Solar Fire" },  // unbound
    {   91263,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "general_husam", "Detonate Traps" },  // verified
    {   92265,   8.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "the-stonecore", "slabhide", "Crystal Storm" },  // verified
    {   96435,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "high_priestess_kilnara", "Tears of Blood" },  // unbound
    {   96457,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "high_priestess_kilnara", "Wave of Agony" },  // verified
    {   96477,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "high_priest_venoxis", "Toxic Link" },  // verified
    {   96684,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "bloodlord_mandokir", "Decapitate" },  // unbound
    {   96740,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "bloodlord_mandokir", "Devastating Slam" },  // verified
    {   96914,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "zanzil", "Zanzili Fire" },  // verified
    {   97172,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "zul-gurub", "jin_do_the_godbreaker", "Shadows of Hakkar" },  // verified
    {  101339,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_jaina", "Frost Blades" },  // verified
    {  101626,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_baine", "Pulverize" },  // unbound
    {  101836,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_baine", "Molten Axe" },  // unbound
    {  101927,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_jaina", "Flarecore" },  // unbound
    {  102149,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_tyrande", "Moonlance" },  // unbound
    {  102241,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_tyrande", "Tears of Elune" },  // unbound
    {  102334,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "well-of-eternity", "queen_azshara", "Servant of the Queen" },  // unbound
    {  102414,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "end-time", "echo_of_tyrande", "Dark Moonlight" },  // unbound
    {  103578,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "archbishop_benedictus", "Purifying Light" },  // unbound
    {  103597,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "asira_dawnslayer", "Throw Knife" },  // unbound
    {  103637,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "lost-city-of-the-tolvir", "siamat", "Chain Lightning" },  // unbound
    {  103651,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "archbishop_benedictus", "Purifying Blast" },  // unbound
    {  103684,  15.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "archbishop_benedictus", "Wave of Virtue" },  // unbound
    {  103769,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "archbishop_benedictus", "Corrupting Twilight" },  // unbound
    {  103781,  15.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "archbishop_benedictus", "Wave of Twilight" },  // unbound
    {  103790,   8.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "hour-of-twilight", "asira_dawnslayer", "Choking Smoke Bomb" },  // unbound
    {  108141,   6.0f, MechanicClass::Avoidable, DispelType::None, InterruptPriority::Default, "well-of-eternity", "perotharn", "Fel Flames" },  // unbound
    };
}
